spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jackson:
    serialization:
      INDENT_OUTPUT: false
      WRITE_ENUMS_USING_TO_STRING: true
      FAIL_ON_EMPTY_BEANS: false
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
build:
  version: '@project.version@'
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    displayOperationId: true
    path: /docs
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/brejanomicon?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.core.StatementCreatorUtils: trace
server:
  port: 8081